# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b92a57283aef5bb8bed5cc87520e42488327cddc31b4e20d0d9d0026c43efa4eb8c108a9109d5db957980665c3f75b1d67a2d721b488748ce1a73447a6e1de

test:
  secret_key_base: 67cb0d4258b5831b7cd48dc300e1ccbca56eea915273dab018035730bb44a0880a15dcf05da218bc117ed555c2f38f91e340b6b1cf68c608229b6234e2e160a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
